name: LightningDeath
api: 3.19.0
authors:
  - provsalt
  - muqsit
  - bypaps
version: 1.3.4
mcpe-protocol: [389, 390, 407, 408, 419, 422, 428, 431]
website: saltcraft.xyz
main: provsalt\lightningdeath\Loader
permissions:
  lightningdeath.bypass:
    default: false
